### ISSUE TITLE
Fix image overflow

### ISSUE THREAD

**Issue by BillieAm** [BillieAm/test-collaboration#5]

**Comment by BillieAm** [comment]
@pilegesh 
You won't believe it!
The image overflow is a Chrome bug. It looks good in other browsers! :)

**Comment by BillieAm** [comment]
Chrome:
<img width="826" alt="Screen Shot 2021-09-28 at 5 02 00" src="https://user-images.githubusercontent.com/24351993/135010309-6771ffba-f098-4afd-9728-5fbc307cff3e.png">


Firefox:
<img width="765" alt="Screen Shot 2021-09-28 at 5 02 12" src="https://user-images.githubusercontent.com/24351993/135010341-277e0513-7a6c-4422-82fd-78c233a15cbc.png">

**Comment by BillieAm** [comment]
It has to do with images and flex-box.
Anyway, fixed it!

**Comment by pilegesh** [comment]
Cool
